export const STRIPE_SECRETS = [
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
] as const;

export const AUTH_SECRETS = ["JWT_SECRET"] as const;

export const AI_API_SECRETS = [
  "GEMINI_API_KEY",
  "GOOGLE_API_KEY",
  "WEB_API_KEY",
] as const;

export const FEDEX_SECRETS = [
  "FEDEX_ENV",
  "FEDEX_BASE_URL",
  "FEDEX_CLIENT_ID",
  "FEDEX_CLIENT_SECRET",
  "FEDEX_ACCOUNT_NUMBER",
  "FEDEX_SHIPPER_CONTACT_NAME",
  "FEDEX_SHIPPER_COMPANY_NAME",
  "FEDEX_SHIPPER_PHONE",
  "FEDEX_SHIPPER_EMAIL",
  "FEDEX_SHIPPER_STREET_1",
  "FEDEX_SHIPPER_STREET_2",
  "FEDEX_SHIPPER_CITY",
  "FEDEX_SHIPPER_STATE_OR_PROVINCE_CODE",
  "FEDEX_SHIPPER_POSTAL_CODE",
  "FEDEX_SHIPPER_COUNTRY_CODE",
  "FEDEX_SHIPPER_RESIDENTIAL",
] as const;

export const LIGA_MX_SECRETS = ["LMX_API_KEY"] as const;

export const LEGACY_CONFIG_SECRETS = [
  "APP_URL",
  "STORE_PUBLIC_BASE_URL",
  "STORE_PRODUCT_PATH_TEMPLATE",
  "AI_STORE_MAPS_URL",
  "AI_STORAGE_BUCKET",
  "GCS_TRYON_BUCKET",
  "AI_PUBLIC_CHAT_ENABLED",
  "AI_PUBLIC_CHAT_RATE_LIMIT_WINDOW_MS",
  "AI_PUBLIC_CHAT_RATE_LIMIT_MAX",
] as const;

export const APLAZO_PAYMENT_SECRETS = [
  "APLAZO_ENABLED",
  "APLAZO_ENV",
  "APLAZO_INTEGRATION_VERSION",
  "APLAZO_ONLINE_ENABLED",
  "APLAZO_REFUNDS_ENABLED",
  "APLAZO_RECONCILE_ENABLED",
  "APLAZO_ONLINE_BASE_URL",
  "APLAZO_ONLINE_MERCHANT_BASE_URL",
  "APLAZO_ONLINE_REFUNDS_BASE_URL",
  "APLAZO_ONLINE_MERCHANT_ID",
  "APLAZO_ONLINE_API_TOKEN",
  "APLAZO_ONLINE_WEBHOOK_SECRET",
  "APLAZO_ONLINE_WEBHOOK_AUTH_SCHEME",
  "APLAZO_ONLINE_TIMEOUT_MS",
  "APLAZO_ONLINE_AUTH_PATH",
  "APLAZO_ONLINE_CREATE_PATH",
  "APLAZO_ONLINE_STATUS_PATH",
  "APLAZO_ONLINE_CANCEL_PATH",
  "APLAZO_ONLINE_REFUND_PATH",
  "APLAZO_ONLINE_REFUND_STATUS_PATH",
] as const;

export const API_RUNTIME_SECRETS = [
  ...AUTH_SECRETS,
  ...STRIPE_SECRETS,
  ...AI_API_SECRETS,
  ...FEDEX_SECRETS,
  ...LIGA_MX_SECRETS,
  ...APLAZO_PAYMENT_SECRETS,
  ...LEGACY_CONFIG_SECRETS,
] as const;

export const PAYMENT_EVENT_SECRETS = [
  ...STRIPE_SECRETS,
  ...APLAZO_PAYMENT_SECRETS,
  ...FEDEX_SECRETS,
  "APP_URL",
] as const;

export const AI_TRIGGER_SECRETS = [
  ...AI_API_SECRETS,
  ...LEGACY_CONFIG_SECRETS,
] as const;

export const NOTIFICATION_EVENT_SECRETS = [
  ...AI_API_SECRETS,
  ...LEGACY_CONFIG_SECRETS,
] as const;
