/**
 * Enumeraciones del módulo POS: roles operativos, capacidades, estados y tipos.
 *
 * Los estados nunca se modifican con un PATCH genérico: toda transición pasa por
 * `domain/state-machines.ts`.
 */

/**
 * Rol operativo dentro del POS. No sustituye a `RolUsuario`: se deriva de él y se refina
 * con el documento `posOperators/{uid}` (DEC-07).
 */
export enum PosRole {
  CASHIER = "CASHIER",
  SENIOR_CASHIER = "SENIOR_CASHIER",
  SUPERVISOR = "SUPERVISOR",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

/** Roles POS asignables manualmente a un usuario con rol base `EMPLEADO`. */
export const ASSIGNABLE_POS_ROLES: readonly PosRole[] = [
  PosRole.CASHIER,
  PosRole.SENIOR_CASHIER,
  PosRole.SUPERVISOR,
];

/** Capacidades atómicas. La autorización siempre se evalúa contra estas, no contra el rol. */
export enum PosCapability {
  ACCESS = "pos.access",
  SALE_CREATE = "pos.sale.create",
  SALE_SUSPEND = "pos.sale.suspend",
  SALE_RESUME = "pos.sale.resume",
  SALE_CANCEL_UNPAID = "pos.sale.cancel_unpaid",
  SALE_CANCEL_PAID = "pos.sale.cancel_paid",
  SALE_DISCOUNT_MANUAL = "pos.sale.discount_manual",
  SALE_REFUND = "pos.sale.refund",
  TICKET_READ = "pos.ticket.read",
  TICKET_REPRINT = "pos.ticket.reprint",

  REGISTER_READ_OWN = "register.read_own",
  REGISTER_READ_ALL = "register.read_all",
  REGISTER_OPEN = "register.open",
  REGISTER_CLOSE = "register.close",
  REGISTER_FORCE_CLOSE = "register.force_close",
  REGISTER_BLOCK = "register.block",

  SHIFT_START = "shift.start",
  SHIFT_END_OWN = "shift.end_own",
  SHIFT_HANDOFF = "shift.handoff",
  SHIFT_READ_OWN = "shift.read_own",
  SHIFT_READ_ALL = "shift.read_all",

  CASH_MOVEMENT_CREATE = "cash_movement.create",
  CASH_MOVEMENT_APPROVE = "cash_movement.approve",
  CASH_DROP_REQUEST = "cash_drop.request",
  CASH_DROP_APPROVE = "cash_drop.approve",
  CASH_TRANSFER_REQUEST = "cash_transfer.request",
  CASH_TRANSFER_CONFIRM = "cash_transfer.confirm",

  CUT_CREATE_OWN = "cut.create_own",
  CUT_READ_OWN = "cut.read_own",
  CUT_READ_ALL = "cut.read_all",
  CUT_REVIEW = "cut.review",
  CUT_APPROVE = "cut.approve",
  CUT_REJECT = "cut.reject",
  CUT_REQUEST_SECOND_COUNT = "cut.request_second_count",
  CUT_REOPEN = "cut.reopen",

  INCIDENT_CREATE = "incident.create",
  INCIDENT_RESOLVE = "incident.resolve",

  DAILY_CLOSE_PREVIEW = "daily_close.preview",
  DAILY_CLOSE_EXECUTE = "daily_close.execute",
  DAILY_CLOSE_FORCE = "daily_close.force",

  REPORT_READ_OWN = "report.read_own",
  REPORT_READ_ALL = "report.read_all",
  AUDIT_READ = "audit.read",
  CONFIG_MANAGE = "pos.config.manage",
}

export enum PosRegisterStatus {
  AVAILABLE = "AVAILABLE",
  OPEN = "OPEN",
  BLOCKED = "BLOCKED",
  MAINTENANCE = "MAINTENANCE",
  ARCHIVED = "ARCHIVED",
}

export enum PosSessionStatus {
  OPEN = "OPEN",
  HANDOFF_PENDING = "HANDOFF_PENDING",
  COUNTING = "COUNTING",
  REVIEW_PENDING = "REVIEW_PENDING",
  CLOSED = "CLOSED",
  FORCED_CLOSED = "FORCED_CLOSED",
}

export enum PosShiftStatus {
  ACTIVE = "ACTIVE",
  HANDOFF_PENDING = "HANDOFF_PENDING",
  COUNTING = "COUNTING",
  SUBMITTED = "SUBMITTED",
  SECOND_COUNT_REQUIRED = "SECOND_COUNT_REQUIRED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ESCALATED = "ESCALATED",
  CLOSED = "CLOSED",
  FORCED_CLOSED = "FORCED_CLOSED",
}

export enum PosSaleStatus {
  DRAFT = "DRAFT",
  SUSPENDED = "SUSPENDED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAID = "PAID",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  REFUNDED = "REFUNDED",
  VOIDED = "VOIDED",
  CANCELLED = "CANCELLED",
}

export enum PosPaymentStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
  CANCELLED = "CANCELLED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  REFUNDED = "REFUNDED",
}

export enum PosPaymentMethod {
  CASH = "CASH",
  CARD_EXTERNAL = "CARD_EXTERNAL",
}

export enum PosCashMovementStatus {
  PENDING_AUTHORIZATION = "PENDING_AUTHORIZATION",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  IN_TRANSIT = "IN_TRANSIT",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}

export enum PosCashMovementType {
  OPENING_FLOAT = "OPENING_FLOAT",
  CASH_SALE = "CASH_SALE",
  CASH_REFUND = "CASH_REFUND",
  CASH_IN = "CASH_IN",
  CASH_OUT = "CASH_OUT",
  SECURITY_DROP = "SECURITY_DROP",
  CASH_REPLENISHMENT = "CASH_REPLENISHMENT",
  TRANSFER_OUT = "TRANSFER_OUT",
  TRANSFER_IN = "TRANSFER_IN",
  SHIFT_HANDOFF = "SHIFT_HANDOFF",
  AUTHORIZED_ADJUSTMENT = "AUTHORIZED_ADJUSTMENT",
}

/** Tipos que el usuario puede solicitar directamente en `POST /cash-movements`. */
export const REQUESTABLE_CASH_MOVEMENT_TYPES: readonly PosCashMovementType[] = [
  PosCashMovementType.CASH_IN,
  PosCashMovementType.CASH_OUT,
  PosCashMovementType.SECURITY_DROP,
  PosCashMovementType.CASH_REPLENISHMENT,
  PosCashMovementType.TRANSFER_OUT,
  PosCashMovementType.AUTHORIZED_ADJUSTMENT,
];

/** Tipos generados por el sistema como efecto de otra operación. */
export const SYSTEM_CASH_MOVEMENT_TYPES: readonly PosCashMovementType[] = [
  PosCashMovementType.OPENING_FLOAT,
  PosCashMovementType.CASH_SALE,
  PosCashMovementType.CASH_REFUND,
  PosCashMovementType.TRANSFER_IN,
  PosCashMovementType.SHIFT_HANDOFF,
];

export enum PosCashCountStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
}

export enum PosCutScope {
  SHIFT = "SHIFT",
  SESSION = "SESSION",
}

export enum PosCutStatus {
  DRAFT = "DRAFT",
  COUNTING = "COUNTING",
  SUBMITTED = "SUBMITTED",
  SECOND_COUNT_REQUIRED = "SECOND_COUNT_REQUIRED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ESCALATED = "ESCALATED",
  REOPENED = "REOPENED",
  CLOSED = "CLOSED",
}

export enum PosCutClassification {
  BALANCED = "BALANCED",
  WITHIN_TOLERANCE = "WITHIN_TOLERANCE",
  SHORTAGE = "SHORTAGE",
  OVERAGE = "OVERAGE",
  CRITICAL_DIFFERENCE = "CRITICAL_DIFFERENCE",
  UNDER_INVESTIGATION = "UNDER_INVESTIGATION",
}

export enum PosDailyCloseStatus {
  DRAFT = "DRAFT",
  BLOCKED = "BLOCKED",
  READY = "READY",
  CLOSED = "CLOSED",
  FORCED_CLOSED = "FORCED_CLOSED",
}

export enum PosReturnStatus {
  DRAFT = "DRAFT",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

/** Condición física declarada de la mercancía devuelta. Solo una repone inventario. */
export enum PosReturnPhysicalCondition {
  RETURNED_RESELLABLE = "RETURNED_RESELLABLE",
  RETURNED_DAMAGED = "RETURNED_DAMAGED",
  NOT_RETURNED = "NOT_RETURNED",
}

export enum PosIncidentType {
  CASH_DIFFERENCE = "CASH_DIFFERENCE",
  FORCED_CLOSE = "FORCED_CLOSE",
  ABANDONED_SESSION = "ABANDONED_SESSION",
  PAYMENT_MISMATCH = "PAYMENT_MISMATCH",
  INVENTORY_MISMATCH = "INVENTORY_MISMATCH",
  TRANSFER_NOT_RECEIVED = "TRANSFER_NOT_RECEIVED",
  SECURITY_DROP_ISSUE = "SECURITY_DROP_ISSUE",
  DUPLICATE_OPERATION = "DUPLICATE_OPERATION",
  TERMINAL_OFFLINE = "TERMINAL_OFFLINE",
  PRINTER_OFFLINE = "PRINTER_OFFLINE",
  PERMISSION_VIOLATION = "PERMISSION_VIOLATION",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  OTHER = "OTHER",
}

export enum PosIncidentSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum PosIncidentStatus {
  OPEN = "OPEN",
  UNDER_REVIEW = "UNDER_REVIEW",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
  ESCALATED = "ESCALATED",
}

export enum PosDiscountOrigin {
  OFFER = "OFFER",
  PROMOTION_CODE = "PROMOTION_CODE",
  MANUAL = "MANUAL",
}

export enum PosExportStatus {
  QUEUED = "QUEUED",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  EXPIRED = "EXPIRED",
}

export enum PosExportType {
  SHIFTS = "SHIFTS",
  SALES = "SALES",
  CASH_MOVEMENTS = "CASH_MOVEMENTS",
  DIFFERENCES = "DIFFERENCES",
  DAILY_SUMMARY = "DAILY_SUMMARY",
  AUDIT_EVENTS = "AUDIT_EVENTS",
}

export enum PosIdempotencyStatus {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum PosAuditEntity {
  REGISTER = "REGISTER",
  SESSION = "SESSION",
  SHIFT = "SHIFT",
  SALE = "SALE",
  PAYMENT = "PAYMENT",
  CASH_MOVEMENT = "CASH_MOVEMENT",
  CASH_COUNT = "CASH_COUNT",
  CUT = "CUT",
  RETURN = "RETURN",
  DAILY_CLOSE = "DAILY_CLOSE",
  INCIDENT = "INCIDENT",
  EXPORT = "EXPORT",
  SETTINGS = "SETTINGS",
  OPERATOR = "OPERATOR",
  TICKET = "TICKET",
}

export enum PosAuditEventType {
  LOGIN_POS = "LOGIN_POS",
  REGISTER_CREATED = "REGISTER_CREATED",
  REGISTER_UPDATED = "REGISTER_UPDATED",
  REGISTER_OPENED = "REGISTER_OPENED",
  REGISTER_BLOCKED = "REGISTER_BLOCKED",
  REGISTER_UNBLOCKED = "REGISTER_UNBLOCKED",
  REGISTER_ARCHIVED = "REGISTER_ARCHIVED",
  REGISTER_CLOSED = "REGISTER_CLOSED",
  REGISTER_FORCE_CLOSED = "REGISTER_FORCE_CLOSED",
  SHIFT_STARTED = "SHIFT_STARTED",
  SHIFT_HANDOFF_REQUESTED = "SHIFT_HANDOFF_REQUESTED",
  SHIFT_HANDOFF_COMPLETED = "SHIFT_HANDOFF_COMPLETED",
  SHIFT_COUNT_STARTED = "SHIFT_COUNT_STARTED",
  SHIFT_ENDED = "SHIFT_ENDED",
  SHIFT_FORCE_CLOSED = "SHIFT_FORCE_CLOSED",
  SALE_CREATED = "SALE_CREATED",
  SALE_UPDATED = "SALE_UPDATED",
  SALE_MANUAL_DISCOUNT_APPLIED = "SALE_MANUAL_DISCOUNT_APPLIED",
  SALE_CODE_APPLIED = "SALE_CODE_APPLIED",
  SALE_CODE_REMOVED = "SALE_CODE_REMOVED",
  SALE_SUSPENDED = "SALE_SUSPENDED",
  SALE_RESUMED = "SALE_RESUMED",
  SALE_CHECKOUT_STARTED = "SALE_CHECKOUT_STARTED",
  SALE_RETURNED_TO_DRAFT = "SALE_RETURNED_TO_DRAFT",
  SALE_CANCELLED = "SALE_CANCELLED",
  SALE_PAID = "SALE_PAID",
  SALE_VOIDED = "SALE_VOIDED",
  PAYMENT_REGISTERED = "PAYMENT_REGISTERED",
  PAYMENT_DECLINED = "PAYMENT_DECLINED",
  PAYMENT_CANCELLED = "PAYMENT_CANCELLED",
  TICKET_READ = "TICKET_READ",
  TICKET_REPRINTED = "TICKET_REPRINTED",
  RETURN_CREATED = "RETURN_CREATED",
  RETURN_APPROVED = "RETURN_APPROVED",
  RETURN_REJECTED = "RETURN_REJECTED",
  REFUND_CREATED = "REFUND_CREATED",
  CASH_MOVEMENT_REQUESTED = "CASH_MOVEMENT_REQUESTED",
  CASH_MOVEMENT_APPROVED = "CASH_MOVEMENT_APPROVED",
  CASH_MOVEMENT_REJECTED = "CASH_MOVEMENT_REJECTED",
  CASH_MOVEMENT_CANCELLED = "CASH_MOVEMENT_CANCELLED",
  CASH_TRANSFER_DISPATCHED = "CASH_TRANSFER_DISPATCHED",
  CASH_TRANSFER_COMPLETED = "CASH_TRANSFER_COMPLETED",
  CASH_COUNT_STARTED = "CASH_COUNT_STARTED",
  CASH_COUNT_SUBMITTED = "CASH_COUNT_SUBMITTED",
  CASH_COUNT_CANCELLED = "CASH_COUNT_CANCELLED",
  SECOND_COUNT_REQUESTED = "SECOND_COUNT_REQUESTED",
  CUT_CLARIFICATION_REQUESTED = "CUT_CLARIFICATION_REQUESTED",
  CUT_APPROVED = "CUT_APPROVED",
  CUT_REJECTED = "CUT_REJECTED",
  CUT_ESCALATED = "CUT_ESCALATED",
  CUT_REOPENED = "CUT_REOPENED",
  DAILY_CLOSE_PREVIEWED = "DAILY_CLOSE_PREVIEWED",
  DAILY_CLOSE_CREATED = "DAILY_CLOSE_CREATED",
  DAILY_CLOSE_FORCED = "DAILY_CLOSE_FORCED",
  INCIDENT_CREATED = "INCIDENT_CREATED",
  INCIDENT_ASSIGNED = "INCIDENT_ASSIGNED",
  INCIDENT_RESOLVED = "INCIDENT_RESOLVED",
  INCIDENT_ESCALATED = "INCIDENT_ESCALATED",
  INCIDENT_DISMISSED = "INCIDENT_DISMISSED",
  REPORT_EXPORTED = "REPORT_EXPORTED",
  SETTINGS_UPDATED = "SETTINGS_UPDATED",
  OPERATOR_UPDATED = "OPERATOR_UPDATED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
}

export enum PosAuditResult {
  SUCCESS = "SUCCESS",
  DENIED = "DENIED",
  FAILURE = "FAILURE",
}
